/*
 * AirPlace:  The Airplace Project is an OpenSource Indoor and Outdoor
 * Localization solution using WiFi RSS (Receive Signal Strength).
 * The AirPlace Project consists of three parts:
 *
 *  1) The AirPlace Logger (Ideal for collecting RSS Logs)
 *  2) The AirPlace Server (Ideal for transforming the collected RSS logs
 *  to meaningful RadioMap files)
 *  3) The AirPlace Tracker (Ideal for using the RadioMap files for
 *  indoor localization)
 *
 * It is ideal for spaces where GPS signal is not sufficient.
 *
 * Authors:
 * C. Laoudias, G.Larkou, G. Constantinou, M. Constantinides, S. Nicolaou,
 *
 * Supervisors:
 * D. Zeinalipour-Yazti and C. G. Panayiotou
 *
 * Copyright (c) 2011, KIOS Research Center and Data Management Systems Lab (DMSL),
 * University of Cyprus. All rights reserved.
 *
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Υou should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on 18-Nov-2010, 03:28:12
 */

package radiomapserver;

import java.awt.Toolkit;

/**
 *
 * @author George
 */
public class About extends javax.swing.JFrame {

    /** Creates new form About */
    public About() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_SocialFace = new javax.swing.JLabel();
        UCY = new javax.swing.JLabel();
        Course = new javax.swing.JLabel();
        javax.swing.JLabel Product_Version = new javax.swing.JLabel();
        javax.swing.JLabel Prof = new javax.swing.JLabel();
        Created = new javax.swing.JLabel();
        DZeina = new javax.swing.JLabel();
        GConst = new javax.swing.JLabel();
        MSavva = new javax.swing.JLabel();
        HHadji = new javax.swing.JLabel();
        Copyright = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        javax.swing.JLabel Version = new javax.swing.JLabel();
        DZeina1 = new javax.swing.JLabel();
        javax.swing.JLabel Prof1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Radio Map Server - About");
        setIconImage(Toolkit.getDefaultToolkit().createImage("./src/SF_icon.png"));

        Logo_SocialFace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        UCY.setFont(new java.awt.Font("Tahoma", 1, 11));
        UCY.setText("University of Cyprus");

        Course.setText("RadioMap Disribution Server");

        Product_Version.setFont(Product_Version.getFont().deriveFont(Product_Version.getFont().getStyle() | java.awt.Font.BOLD));
        Product_Version.setText("Product Version:");

        Prof.setFont(Prof.getFont().deriveFont(Prof.getFont().getStyle() | java.awt.Font.BOLD));
        Prof.setText("Professor:");

        Created.setFont(new java.awt.Font("Tahoma", 1, 11));
        Created.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Created.setText("Undergraduate Students");

        DZeina.setText(" Dr. Demetris Zeinalipour");

        GConst.setText("George Constantinou");

        MSavva.setText("Marios Constantinides");

        HHadji.setText("Silouanos Nicolaou");

        Copyright.setFont(new java.awt.Font("Tahoma", 1, 11));
        Copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Copyright.setText("Copyrights 2011");
        Copyright.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        Version.setText("1.0");

        DZeina1.setText("Christos Laoudias");

        Prof1.setFont(Prof1.getFont().deriveFont(Prof1.getFont().getStyle() | java.awt.Font.BOLD));
        Prof1.setText("Ph.D. Candidate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo_SocialFace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(CloseButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Copyright, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Prof1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DZeina1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Created)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GConst)
                                    .addComponent(MSavva)
                                    .addComponent(HHadji)))
                            .addComponent(Course)
                            .addComponent(UCY)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Product_Version)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Version))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Prof)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DZeina)))
                        .addGap(244, 244, 244)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo_SocialFace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(UCY, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Course)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product_Version)
                    .addComponent(Version))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prof)
                    .addComponent(DZeina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prof1)
                    .addComponent(DZeina1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Created)
                    .addComponent(GConst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MSavva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HHadji)
                .addGap(18, 18, 18)
                .addComponent(Copyright)
                .addGap(18, 18, 18)
                .addComponent(CloseButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel Course;
    private javax.swing.JLabel Created;
    private javax.swing.JLabel DZeina;
    private javax.swing.JLabel DZeina1;
    private javax.swing.JLabel GConst;
    private javax.swing.JLabel HHadji;
    private javax.swing.JLabel Logo_SocialFace;
    private javax.swing.JLabel MSavva;
    private javax.swing.JLabel UCY;
    // End of variables declaration//GEN-END:variables

}
